name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build React app
        run: |
          npm install
          npm run build

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SERVER_KEY }}" > server_key.pem
          chmod 600 server_key.pem

      - name: Upload build files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i server_key.pem -r dist/* ec2-user@${{ secrets.SERVER_HOST }}:~/deploy_tmp/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i server_key.pem ec2-user@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r ~/deploy_tmp/* /usr/share/nginx/html/
            sudo chown -R nginx:nginx /usr/share/nginx/html/
          EOF

      - name: Cleanup
        run: rm server_key.pem
